services:
  express_app:
    image: alvi0/first:latest
    ports:
      - 8080:8080
    restart: always
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
